/**
 * TaskmemoLogger — main.js
 * Wails v2 frontend controller (Vanilla JS, no framework)
 *
 * Bindings are auto-generated by `wails dev` / `wails build` into:
 *   ../wailsjs/go/main/App.js
 */
import { SaveLog, SaveWorkStart, GetRecentLogs, GetTagSuggestions, HasWorkStartToday } from '../wailsjs/go/main/App.js';
import { Quit, EventsOn } from '../wailsjs/runtime/runtime.js';

// ── DOM refs ──────────────────────────────────────────────────────────────────
const chatArea = document.getElementById('chatArea');
const chatEmpty = document.getElementById('chatEmpty');
const tagPillsArea = document.getElementById('tagPillsArea');
const tagInput = document.getElementById('tagInput');
const suggestionList = document.getElementById('suggestionList');
const taskInput = document.getElementById('taskInput');
const submitBtn = document.getElementById('submitBtn');
const hintText = document.getElementById('hintText');
const timeOffset = document.getElementById('timeOffset');
const workStartBtn = document.getElementById('workStartBtn');

// ── State ─────────────────────────────────────────────────────────────────────
/** @type {string[]} Currently selected tags */
let selectedTags = [];
/** @type {string[]} Current suggestion candidates */
let suggestions = [];
/** @type {number} Keyboard-highlighted suggestion index (-1 = none) */
let suggestionIndex = -1;

// ── Init ──────────────────────────────────────────────────────────────────────
window.addEventListener('DOMContentLoaded', async () => {
  // Go側のOnDomReadyからWindowShow完了後に発火されるイベントを待ち受ける
  // データロードより先に登録しておくことで、タイミングによる取りこぼしを防ぐ
  EventsOn('app:ready-focus', () => {
    focusTagInput();
  });

  await loadRecentLogs();
  await checkWorkStartGuard();
});

// ウィンドウがOSからフォーカスを獲得した時（Alt+Tab等での復帰時）
window.addEventListener('focus', () => {
  focusTagInput();
});

/**
 * タグ入力欄にフォーカスを当て、キャレットを表示させるヘルパー。
 * Win32レベルでOSのキーボードフォーカスが既に確保されている前提のため、
 * blur() や requestAnimationFrame 等のハックなしで直接フォーカスする。
 */
function focusTagInput() {
  if (document.activeElement === taskInput) return;
  tagInput.focus();
  tagInput.select(); // select()でキャレットレンダリングを確実に促す
}

// ── Load recent logs into chat history ───────────────────────────────────────
async function loadRecentLogs() {
  const entries = await GetRecentLogs();
  if (!entries || entries.length === 0) return;
  chatEmpty.style.display = 'none';
  entries.forEach(renderBubble);
  scrollToBottom();
}

/**
 * 本日すでに「始業」エントリが登録されていれば、始業ボタンを無効化します（1日1回制限）。
 */
async function checkWorkStartGuard() {
  try {
    const alreadyStarted = await HasWorkStartToday();
    if (alreadyStarted) {
      workStartBtn.disabled = true;
      workStartBtn.title = '本日の始業はすでに記録済みです';
    }
  } catch (err) {
    console.error('始業状況の取得に失敗しました:', err);
  }
}

/**
 * タイムスタンプ文字列 "YYYY-MM-DD HH:MM" を表示用にフォーマットする。
 * 今日のエントリ → "HH:MM"
 * 過去日のエントリ → "MM/DD HH:MM"
 * @param {string} ts
 * @returns {string}
 */
function formatTimestamp(ts) {
  if (!ts) return '';
  const today = formatDateToTimestamp(new Date()).slice(0, 10); // "YYYY-MM-DD"
  const entryDate = ts.slice(0, 10);                   // "YYYY-MM-DD"
  if (entryDate === today) {
    return ts.slice(11);                               // "HH:MM"
  }
  return ts.slice(5, 10).replace('-', '/') + ' ' + ts.slice(11); // "MM/DD HH:MM"
}

/**
 * @param {{ timestamp: string, tags: string[], text: string }} entry
 */
function renderBubble(entry) {
  const bubble = document.createElement('div');
  bubble.className = 'chat-bubble';
  if (entry.tags && entry.tags.includes('始業')) {
    bubble.classList.add('bubble-work-start');
  }

  const meta = document.createElement('div');
  meta.className = 'bubble-meta';

  const timeEl = document.createElement('span');
  timeEl.className = 'bubble-time';
  timeEl.textContent = formatTimestamp(entry.timestamp);
  meta.appendChild(timeEl);

  if (entry.tags && entry.tags.length > 0) {
    const tagsEl = document.createElement('div');
    tagsEl.className = 'bubble-tags';
    entry.tags.forEach(t => {
      const pill = document.createElement('span');
      pill.className = 'bubble-tag';
      pill.textContent = t;
      tagsEl.appendChild(pill);
    });
    meta.appendChild(tagsEl);
  }

  const textEl = document.createElement('p');
  textEl.className = 'bubble-text';
  textEl.textContent = entry.text || '';

  bubble.appendChild(meta);
  bubble.appendChild(textEl);
  chatArea.appendChild(bubble);
}

function scrollToBottom() {
  chatArea.scrollTop = chatArea.scrollHeight;
}

// ── Tag pill management ───────────────────────────────────────────────────────
function addTag(tag) {
  tag = tag.trim();
  if (!tag) return;
  // Prevent duplicate (case-insensitive)
  if (selectedTags.some(t => t.toLowerCase() === tag.toLowerCase())) {
    tagInput.value = '';
    hideSuggestions();
    return;
  }
  selectedTags.push(tag);
  renderPills();
  tagInput.value = '';
  hideSuggestions();
}

function removeTag(index) {
  selectedTags.splice(index, 1);
  renderPills();
  tagInput.focus();
}

function renderPills() {
  // Remove existing pills (keep the input)
  tagPillsArea.querySelectorAll('.tag-pill').forEach(el => el.remove());

  selectedTags.forEach((tag, i) => {
    const pill = document.createElement('span');
    pill.className = 'tag-pill';
    pill.textContent = tag;

    const removeBtn = document.createElement('button');
    removeBtn.className = 'pill-remove';
    removeBtn.textContent = '×';
    removeBtn.setAttribute('aria-label', `タグ「${tag}」を削除`);
    removeBtn.addEventListener('mousedown', e => {
      e.preventDefault(); // prevent blur
      removeTag(i);
    });

    pill.appendChild(removeBtn);
    tagPillsArea.insertBefore(pill, tagInput);
  });
}

// ── Tag suggestion logic ──────────────────────────────────────────────────────
tagInput.addEventListener('input', async () => {
  const prefix = tagInput.value.trim();
  if (prefix === '') {
    hideSuggestions();
    return;
  }
  suggestions = await GetTagSuggestions(prefix);
  // Filter already-selected
  suggestions = suggestions.filter(
    s => !selectedTags.some(t => t.toLowerCase() === s.toLowerCase())
  );
  showSuggestions(suggestions);
});

tagInput.addEventListener('keydown', e => {
  // IME入力中（変換の確定など）のキーイベントは無視する
  if (e.isComposing) return;

  if (suggestionList.hidden) {
    if (e.key === 'Enter' && tagInput.value.trim()) {
      e.preventDefault();
      addTag(tagInput.value.trim());
      return;
    }
    if (e.key === 'Backspace' && tagInput.value === '' && selectedTags.length > 0) {
      removeTag(selectedTags.length - 1);
      return;
    }
    if (e.key === 'Tab') {
      e.preventDefault();
      const pendingTag = tagInput.value.trim();
      if (pendingTag) {
        addTag(pendingTag);
      }
      taskInput.focus();
      return;
    }
    return;
  }

  // Suggestion list is open
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    suggestionIndex = Math.min(suggestionIndex + 1, suggestions.length - 1);
    updateSuggestionHighlight();
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    suggestionIndex = Math.max(suggestionIndex - 1, -1);
    updateSuggestionHighlight();
  } else if (e.key === 'Enter') {
    e.preventDefault();
    if (suggestionIndex >= 0) {
      addTag(suggestions[suggestionIndex]);
    } else if (tagInput.value.trim()) {
      addTag(tagInput.value.trim());
    }
  } else if (e.key === 'Escape') {
    hideSuggestions();
  } else if (e.key === 'Tab') {
    e.preventDefault();
    hideSuggestions();
    const pendingTag = tagInput.value.trim();
    if (pendingTag) {
      addTag(pendingTag);
    }
    taskInput.focus();
  }
});

tagPillsArea.addEventListener('click', () => tagInput.focus());

function showSuggestions(items) {
  suggestionList.innerHTML = '';
  suggestionIndex = -1;

  if (items.length === 0) {
    hideSuggestions();
    return;
  }

  items.forEach((item, i) => {
    const li = document.createElement('li');
    li.className = 'suggestion-item';
    li.role = 'option';
    li.id = `suggestion-${i}`;
    li.textContent = item;
    li.addEventListener('mousedown', e => {
      e.preventDefault();
      addTag(item);
    });
    suggestionList.appendChild(li);
  });

  suggestionList.hidden = false;
  tagInput.setAttribute('aria-expanded', 'true');
}

function hideSuggestions() {
  suggestionList.hidden = true;
  suggestionList.innerHTML = '';
  suggestionIndex = -1;
  tagInput.setAttribute('aria-expanded', 'false');
}

function updateSuggestionHighlight() {
  const items = suggestionList.querySelectorAll('.suggestion-item');
  items.forEach((el, i) => {
    el.setAttribute('aria-selected', i === suggestionIndex ? 'true' : 'false');
  });
  tagInput.setAttribute('aria-activedescendant',
    suggestionIndex >= 0 ? `suggestion-${suggestionIndex}` : '');
}

// Close suggestions when clicking outside
document.addEventListener('mousedown', e => {
  if (!tagPillsArea.contains(e.target) && !suggestionList.contains(e.target)) {
    hideSuggestions();
  }
});

// ── Time helper (新規バブル生成用) ───────────────────────────────────────
/**
 * Date オブジェクトを "YYYY-MM-DD HH:MM" 形式の文字列に変換します。
 * 新規バブル生成時に使用（バックエンドから取得した timestamp 文字列と区別するため formatDateToTimestamp と命名）
 * @param {Date} date
 * @returns {string}
 */
function formatDateToTimestamp(date) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  const hh = String(date.getHours()).padStart(2, '0');
  const mm = String(date.getMinutes()).padStart(2, '0');
  return `${y}-${m}-${d} ${hh}:${mm}`;
}

// ── Submit ────────────────────────────────────────────────────────────────────
async function submit() {
  // 未確定のタグがあれば追加する
  const pendingTag = tagInput.value.trim();
  if (pendingTag) {
    addTag(pendingTag);
  }

  const text = taskInput.value.trim();
  if (!text) {
    hintText.textContent = 'タスク内容を入力してください';
    taskInput.focus();
    setTimeout(() => { hintText.textContent = ''; }, 2000);
    return;
  }

  // Disable UI during save
  submitBtn.disabled = true;
  hintText.textContent = '保存中...';

  try {
    const offset = parseInt(timeOffset.value, 10);
    await SaveLog(selectedTags, text, offset);

    // Show saved bubble
    const t = new Date(Date.now() + offset * 60000);
    const entry = {
      timestamp: formatDateToTimestamp(t),
      tags: [...selectedTags],
      text
    };
    chatEmpty.style.display = 'none';
    renderBubble(entry);
    scrollToBottom();

    // Brief pause then quit
    await new Promise(r => setTimeout(r, 250));
    Quit();

  } catch (err) {
    hintText.textContent = `保存に失敗しました: ${err}`;
    submitBtn.disabled = false;
  }
}

// ── Work Start ────────────────────────────────────────────────────────────────
workStartBtn.addEventListener('click', async () => {
  workStartBtn.disabled = true;
  hintText.textContent = '始業を記録中...';

  try {
    const offset = parseInt(timeOffset.value, 10);
    await SaveWorkStart(offset);

    // Show saved bubble
    const t = new Date(Date.now() + offset * 60000);
    const entry = {
      timestamp: formatDateToTimestamp(t),
      tags: ['始業'],
      text: '始業'
    };
    chatEmpty.style.display = 'none';
    renderBubble(entry);
    scrollToBottom();

    // Brief pause then quit
    await new Promise(r => setTimeout(r, 250));
    Quit();

  } catch (err) {
    hintText.textContent = `始業の記録に失敗しました: ${err}`;
    workStartBtn.disabled = false;
  }
});

// Ctrl+Enter globally
document.addEventListener('keydown', e => {
  if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
    e.preventDefault();
    submit();
  }
});

submitBtn.addEventListener('click', submit);
