/**
 * TaskmemoLogger — main.js
 * Wails v2 frontend controller (Vanilla JS, no framework)
 *
 * Bindings are auto-generated by `wails dev` / `wails build` into:
 *   ../wailsjs/go/main/App.js
 */
import { SaveLog, GetTodayLogs, GetTagSuggestions } from '../wailsjs/go/main/App.js';
import { Quit, EventsOn } from '../wailsjs/runtime/runtime.js';

// ── DOM refs ──────────────────────────────────────────────────────────────────
const chatArea = document.getElementById('chatArea');
const chatEmpty = document.getElementById('chatEmpty');
const tagPillsArea = document.getElementById('tagPillsArea');
const tagInput = document.getElementById('tagInput');
const suggestionList = document.getElementById('suggestionList');
const taskInput = document.getElementById('taskInput');
const submitBtn = document.getElementById('submitBtn');
const hintText = document.getElementById('hintText');

// ── State ─────────────────────────────────────────────────────────────────────
/** @type {string[]} Currently selected tags */
let selectedTags = [];
/** @type {string[]} Current suggestion candidates */
let suggestions = [];
/** @type {number} Keyboard-highlighted suggestion index (-1 = none) */
let suggestionIndex = -1;

// ── Init ──────────────────────────────────────────────────────────────────────
window.addEventListener('DOMContentLoaded', async () => {
  await loadTodayLogs();

  // Go側のOnDomReadyからWindowShow完了後に発火されるイベントを待ち受ける
  EventsOn('app:ready-focus', () => {
    focusTagInput();
  });
});

// ウィンドウがOSからフォーカスを獲得した時（Alt+Tab等での復帰時）
window.addEventListener('focus', () => {
  focusTagInput();
});

/**
 * タグ入力欄にフォーカスを当て、キャレットを確実に表示させるヘルパー。
 * taskInputに既にフォーカスがある場合は邪魔をしない。
 */
function focusTagInput() {
  if (document.activeElement === taskInput) return;
  tagInput.blur();
  // requestAnimationFrameで次描画フレームまで待機し、
  // WebView2のレンダリングパイプラインとフォーカス状態を同期させる
  requestAnimationFrame(() => {
    tagInput.focus();
    tagInput.select(); // select()でキャレットレンダリングを強制
  });
}

// ── Load today's logs into chat history ───────────────────────────────────────
async function loadTodayLogs() {
  const entries = await GetTodayLogs();
  if (!entries || entries.length === 0) return;
  chatEmpty.style.display = 'none';
  entries.forEach(renderBubble);
  scrollToBottom();
}

/**
 * @param {{ timestamp: string, tags: string[], text: string }} entry
 */
function renderBubble(entry) {
  const bubble = document.createElement('div');
  bubble.className = 'chat-bubble';

  const meta = document.createElement('div');
  meta.className = 'bubble-meta';

  const timeEl = document.createElement('span');
  timeEl.className = 'bubble-time';
  // Show only HH:MM from "YYYY-MM-DD HH:MM"
  timeEl.textContent = entry.timestamp ? entry.timestamp.slice(11) : '';
  meta.appendChild(timeEl);

  if (entry.tags && entry.tags.length > 0) {
    const tagsEl = document.createElement('div');
    tagsEl.className = 'bubble-tags';
    entry.tags.forEach(t => {
      const pill = document.createElement('span');
      pill.className = 'bubble-tag';
      pill.textContent = t;
      tagsEl.appendChild(pill);
    });
    meta.appendChild(tagsEl);
  }

  const textEl = document.createElement('p');
  textEl.className = 'bubble-text';
  textEl.textContent = entry.text || '';

  bubble.appendChild(meta);
  bubble.appendChild(textEl);
  chatArea.appendChild(bubble);
}

function scrollToBottom() {
  chatArea.scrollTop = chatArea.scrollHeight;
}

// ── Tag pill management ───────────────────────────────────────────────────────
function addTag(tag) {
  tag = tag.trim();
  if (!tag) return;
  // Prevent duplicate (case-insensitive)
  if (selectedTags.some(t => t.toLowerCase() === tag.toLowerCase())) {
    tagInput.value = '';
    hideSuggestions();
    return;
  }
  selectedTags.push(tag);
  renderPills();
  tagInput.value = '';
  hideSuggestions();
}

function removeTag(index) {
  selectedTags.splice(index, 1);
  renderPills();
  tagInput.focus();
}

function renderPills() {
  // Remove existing pills (keep the input)
  tagPillsArea.querySelectorAll('.tag-pill').forEach(el => el.remove());

  selectedTags.forEach((tag, i) => {
    const pill = document.createElement('span');
    pill.className = 'tag-pill';
    pill.textContent = tag;

    const removeBtn = document.createElement('button');
    removeBtn.className = 'pill-remove';
    removeBtn.textContent = '×';
    removeBtn.setAttribute('aria-label', `タグ「${tag}」を削除`);
    removeBtn.addEventListener('mousedown', e => {
      e.preventDefault(); // prevent blur
      removeTag(i);
    });

    pill.appendChild(removeBtn);
    tagPillsArea.insertBefore(pill, tagInput);
  });
}

// ── Tag suggestion logic ──────────────────────────────────────────────────────
tagInput.addEventListener('input', async () => {
  const prefix = tagInput.value.trim();
  if (prefix === '') {
    hideSuggestions();
    return;
  }
  suggestions = await GetTagSuggestions(prefix);
  // Filter already-selected
  suggestions = suggestions.filter(
    s => !selectedTags.some(t => t.toLowerCase() === s.toLowerCase())
  );
  showSuggestions(suggestions);
});

tagInput.addEventListener('keydown', e => {
  // IME入力中（変換の確定など）のキーイベントは無視する
  if (e.isComposing) return;

  if (suggestionList.hidden) {
    if (e.key === 'Enter' && tagInput.value.trim()) {
      e.preventDefault();
      addTag(tagInput.value.trim());
      return;
    }
    if (e.key === 'Backspace' && tagInput.value === '' && selectedTags.length > 0) {
      removeTag(selectedTags.length - 1);
      return;
    }
    if (e.key === 'Tab') {
      e.preventDefault();
      const pendingTag = tagInput.value.trim();
      if (pendingTag) {
        addTag(pendingTag);
      }
      taskInput.focus();
      return;
    }
    return;
  }

  // Suggestion list is open
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    suggestionIndex = Math.min(suggestionIndex + 1, suggestions.length - 1);
    updateSuggestionHighlight();
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    suggestionIndex = Math.max(suggestionIndex - 1, -1);
    updateSuggestionHighlight();
  } else if (e.key === 'Enter') {
    e.preventDefault();
    if (suggestionIndex >= 0) {
      addTag(suggestions[suggestionIndex]);
    } else if (tagInput.value.trim()) {
      addTag(tagInput.value.trim());
    }
  } else if (e.key === 'Escape') {
    hideSuggestions();
  } else if (e.key === 'Tab') {
    e.preventDefault();
    hideSuggestions();
    const pendingTag = tagInput.value.trim();
    if (pendingTag) {
      addTag(pendingTag);
    }
    taskInput.focus();
  }
});

tagPillsArea.addEventListener('click', () => tagInput.focus());

function showSuggestions(items) {
  suggestionList.innerHTML = '';
  suggestionIndex = -1;

  if (items.length === 0) {
    hideSuggestions();
    return;
  }

  items.forEach((item, i) => {
    const li = document.createElement('li');
    li.className = 'suggestion-item';
    li.role = 'option';
    li.id = `suggestion-${i}`;
    li.textContent = item;
    li.addEventListener('mousedown', e => {
      e.preventDefault();
      addTag(item);
    });
    suggestionList.appendChild(li);
  });

  suggestionList.hidden = false;
  tagInput.setAttribute('aria-expanded', 'true');
}

function hideSuggestions() {
  suggestionList.hidden = true;
  suggestionList.innerHTML = '';
  suggestionIndex = -1;
  tagInput.setAttribute('aria-expanded', 'false');
}

function updateSuggestionHighlight() {
  const items = suggestionList.querySelectorAll('.suggestion-item');
  items.forEach((el, i) => {
    el.setAttribute('aria-selected', i === suggestionIndex ? 'true' : 'false');
  });
  tagInput.setAttribute('aria-activedescendant',
    suggestionIndex >= 0 ? `suggestion-${suggestionIndex}` : '');
}

// Close suggestions when clicking outside
document.addEventListener('mousedown', e => {
  if (!tagPillsArea.contains(e.target) && !suggestionList.contains(e.target)) {
    hideSuggestions();
  }
});

// ── Submit ────────────────────────────────────────────────────────────────────
async function submit() {
  // 未確定のタグがあれば追加する
  const pendingTag = tagInput.value.trim();
  if (pendingTag) {
    addTag(pendingTag);
  }

  const text = taskInput.value.trim();
  if (!text) {
    hintText.textContent = 'タスク内容を入力してください';
    taskInput.focus();
    setTimeout(() => { hintText.textContent = ''; }, 2000);
    return;
  }

  // Disable UI during save
  submitBtn.disabled = true;
  hintText.textContent = '保存中...';

  try {
    await SaveLog(selectedTags, text);

    // Show saved bubble
    const entry = {
      timestamp: new Date().toLocaleString('ja-JP', {
        year: 'numeric', month: '2-digit', day: '2-digit',
        hour: '2-digit', minute: '2-digit'
      }).replace(/\//g, '-'),
      tags: [...selectedTags],
      text
    };
    chatEmpty.style.display = 'none';
    renderBubble(entry);
    scrollToBottom();

    // Brief pause then quit
    await new Promise(r => setTimeout(r, 250));
    Quit();

  } catch (err) {
    hintText.textContent = `保存に失敗しました: ${err}`;
    submitBtn.disabled = false;
  }
}

// Ctrl+Enter globally
document.addEventListener('keydown', e => {
  if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
    e.preventDefault();
    submit();
  }
});

submitBtn.addEventListener('click', submit);
