// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1) {
  return window['go']['main']['App']['AddTag'](arg1);
}

export function GetRecentLogs() {
  return window['go']['main']['App']['GetRecentLogs']();
}

export function GetTagSuggestions(arg1) {
  return window['go']['main']['App']['GetTagSuggestions'](arg1);
}

export function SaveLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveLog'](arg1, arg2, arg3);
}

export function SaveWorkStart(arg1) {
  return window['go']['main']['App']['SaveWorkStart'](arg1);
}
