// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1) {
  return window['go']['main']['App']['AddTag'](arg1);
}

export function GetTagSuggestions(arg1) {
  return window['go']['main']['App']['GetTagSuggestions'](arg1);
}

export function GetTodayLogs() {
  return window['go']['main']['App']['GetTodayLogs']();
}

export function SaveLog(arg1, arg2) {
  return window['go']['main']['App']['SaveLog'](arg1, arg2);
}
