// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTag(arg1:string):Promise<void>;

export function GetRecentLogs():Promise<Array<main.LogEntry>>;

export function GetTagSuggestions(arg1:string):Promise<Array<string>>;

export function SaveLog(arg1:Array<string>,arg2:string):Promise<void>;
